# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'demo_M08' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demo_M08

  target 'demo_M08Tests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end

end
